image: openjdk:11

stages:
  - build
  - test
  - deploy

before_script:
  - echo "Start CI"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build project
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - feature/ci-cd

test:
  stage: test project
  script:
    - ./gradlew check

after_script:
  - echo "End CI"